### ISSUE TITLE
Breaks after pausing and resuming

### ISSUE THREAD

**Issue by benadamstyles** [groktools/flozone#1]
Hi! This is genuinely an amazing idea and I think it will change my work life to some extent. I work in a loud, distracting office with many people asking me to do different things and the problem this package wants to solve is one that I experience on an hourly basis.

Just found a bug though – after hitting `pause`, and then `resume`, the `pause` button no longer works (or doesn't appear to – it just stays as `pause`) and even clicking `stop` doesn't fix it. If you need any info from me just say, but I'm using the latest version of atom, on Mac OSX.

**Comment by benadamstyles** [comment]
Also if I can help out in any way just let me know!

**Comment by vinodkd** [comment]
Hi,
Thanks for trying my plugin out! I'd really not expected anyone to use it already. You're right this is an issue. I'll take a look and respond back here.
Btw, I'm planning on making the interaction even simpler, something like so:
- No need for start/stop button: entering a new task = start of task = stop of prev task
- Add timer that shows either (a)time worked on task or (b) start time of task
- Keep the pause button
- When pause hit, change timer to show time away from task
- ..And then have the replay button to its right, which now makes sense to hit - the longer you've been away from the task

Thanks for offering to help. If you have experience with Atom, maybe you could tell me how to fix the tab order. I'm a keyboarder and would like to tab from the task name text box to the start button and havent yet figured out how to do that. Similarly, not sure if the timer idea will pan out within Atom, but am going to try.

Oh, and if you'd like to: please fork it/submit a pull request, etc. Its the github environment, after all.

Btw, this is part of a set of tools I'm building as part of an online masters I'm doing at Georgia tech. Feel free to check out the others at the [groktools github org](https://github.com/groktools). There is one in particular - lilbro - that I'd like to integrate with flozone because Atom doesnt seem to have an app-wide history. If I did integrate with lilbro, I'd be able to do rewind/replay across multiple panes where it would make true sense.

**Comment by vinodkd** [comment]
This should be fixed now with patch version 0.2.1. Please take a look and let me know if you see anything still not quite right.

**Comment by benadamstyles** [comment]
This is fixed now
