### ISSUE TITLE
Redo loop

### ISSUE THREAD

**Issue by benadamstyles** [groktools/flozone#3]
Thanks for responding to my other issue! I have just submitted a PR with some styling adjustments, hope they're ok. I'm not experienced with writing atom packages but I am experienced with web/JS generally so I will have a go. The only problem is I have real difficulty with CoffeeScript, something about it just generally confuses me and puts me off, but we'll see...

I fully agree about the start/stop button not being necessary. However, I must say that a timer would probably actually stop me using this package. I used to time my freelance hours but I realized that the cognitive load of having my work timed was causing me stress and anxiety – as soon as I stopped the timer, my shoulders relaxed, and my thoughts were calmer and more effective. So if you do add a timer, I would really recommend including a user setting to hide it. Showing time _away_ from task would be ok though and quite a good idea I think. Showing start time of task would also be ok for me personally.

On to this issue – I have discovered a redo loop, when you hit the replay button. Haven't had time to check why it happens but I just hit replay and the redo got stuck in an infinite loop. I definitely didn't change `button` to `span` that many times...!

**Comment by vinodkd** [comment]
Coffeescript irritates me too because of its minor idiosyncrasies. I just took the path of least resistance since the package generator creates coffeescript code by default. I'm honestly not proud of the cascading setInterval calls to make the undo/redo work. There's probably a better solution based on reactive principles that are already in atom, but i don't know enough of how that works to do it better.

As for the design changes, thanks for feedback on  start/stop. Agree on the timer for each task being annoying. I originally wanted to add a timer for the interruption (so you could shoo people away :) ) and then thought that the control could still be visible when on the task!

As for the issue, can you give me some specific steps to reproduce? I just tried replaying multiple times and didnt see the loop.

**Comment by benadamstyles** [comment]
I'll try it again and see if I can pin it down to specific circumstances.

**Comment by vinodkd** [comment]
ok thanks.
